### ISSUE TITLE
Ошибка перевода

### ISSUE THREAD

**Issue by andpago** [mipt-cs-on-cpp/course-site#1]
Числитель по-английски numerator, а не nominator
(работа 7)

http://www.multitran.ru/c/m.exe?l1=1&l2=2&s=%F7%E8%F1%EB%E8%F2%E5%EB%FC
http://www.multitran.ru/c/m.exe?l1=2&l2=1&s=nominator

**Comment by tkhirianov** [comment]
Починил в f904a3f
