### ISSUE TITLE
Лабораторная работа: Вычислительная геометрия

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-cpp/course-site#2]
**Лабораторная работа: Вычислительная геометрия**
1. Объект Vector2D
2. Перегрузка оператора вывода
3. Оператор сложения векторов
4. Скалярное умножение векторов
5. Умножение вектора на число и числа на вектор

Придумать упражнения

**Comment by fufler** [comment]
Залил, можно смотреть.
