### ISSUE TITLE
1-я неделя. Практика: компиляция и работа в консоли.

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-cpp/course-site#3]
Компиляция в консоли.
Работа в IDE. Отладка программы.

Алексей, ответственное дело, поэтобу тебе. Ты должен будешь проверить, что всё окружение, необходимое для компиляции, работает.

**Comment by tkhirianov** [comment]
Алексей, сам выбери будем мы сразу давать IDE или всё-таки вначале чистая консоль и clang впридачу.

**Comment by fufler** [comment]
Отладку пока не рассказываем вообще — они пока ещё базовый синтаксис не знают. Тулчейн и IDE (возможно) дадим на следующей работе.
